#!/bin/sh
# Gradle start up script for POSIX-compliant shells.
# Standard wrapper script generated by Gradle. If Android Studio reports the
# wrapper jar is missing, open the project and choose "Sync Project with
# Gradle Files" — Android Studio will offer to regenerate it automatically,
# or run: gradle wrapper --gradle-version 8.4

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_HOME=$(cd "$(dirname "$0")" && pwd)

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

exec java $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
